[vjap-25] [vjap-26]
valtech-ch/microservice-kubernetes-cluster pull request #88
Opened 2021-05-04 13:37 UTC by egrozdani

fixed sonar vulnerabilities, moved common security configuration to a separate module, fixed spodbugs path traversal owasp finding

2021-05-04 15:13 UTC, lrohner requested changes

2021-05-04 15:13 UTC, lrohner commented on security/src/main/java/ch/valtech/kubernetes/microservice/cluster/security/config/KafkaTopicConfiguration.java
> +package ch.valtech.kubernetes.microservice.cluster.security.config;
I don't think we should move Kafka Config, it's not security related.

2021-05-04 15:13 UTC, lrohner commented on functions/src/main/java/ch/valtech/kubernetes/microservice/cluster/function/Config.java
> +          context.getLogger().info(() -> "Function: " + context.getFunctionName() + " is reversing " + value);
Why this function?

2021-05-04 15:13 UTC, lrohner commented on security/build.gradle
> +    id 'org.springframework.boot' version '2.4.5'
You can remove the boot plugin as we don't build a bootJar

2021-05-04 15:13 UTC, lrohner commented on security/build.gradle
> +bootJar {
And remove this after removing boot plugin

2021-05-04 15:13 UTC, lrohner commented on security/build.gradle
> +    implementation 'net.logstash.logback:logstash-logback-encoder:6.6'
logback not need as just a library project

2021-05-04 15:13 UTC, lrohner commented on security/build.gradle
> +    implementation 'org.springframework.kafka:spring-kafka:2.7.0'
Same kafka, should not go to security

2021-05-05 07:06 UTC, egrozdani commented on functions/src/main/java/ch/valtech/kubernetes/microservice/cluster/function/Config.java
> +          context.getLogger().info(() -> "Function: " + context.getFunctionName() + " is reversing " + value);
It is a code smell by Sonar https://sonar.infocentric.ch/project/issues?id=microservice-kubernetes-cluster&open=AXjLGJbigiVO85PxN4BD&resolved=false&sinceLeakPeriod=true and one of the compliant solutions is to use a supplier which is evaluated lazily

2021-05-05 08:28 UTC, merged